---
- name: Check if ReadyAPI is already installed
  ansible.builtin.stat:
    path: "{{ readyapi_install_dir }}"
  register: readyapi_already_installed
  become: true

- name: Include Install
  ansible.builtin.include_tasks: install.yml
  when: not readyapi_uninstall and not readyapi_already_installed.stat.exists

- name: Include uninstall
  ansible.builtin.include_tasks: uninstall.yml
  when: readyapi_uninstall and readyapi_already_installed.stat.exists

- name: Include cleanup tasks.
  ansible.builtin.include_tasks: cleanup.yml
  when: readyapi_cleanup
