---
- name: Uninstall ReadyAPI
  ansible.builtin.command: "{{ readyapi_install_dir }}/uninstall -q"
  changed_when: false
  become: true

- name: Find all ReadyAPI desktop files
  ansible.builtin.find:
    paths: /usr/share/applications,/usr/local/share/applications
    file_type: file
    patterns: "*.desktop"
    contains: "Name=ReadyAPI {{ readyapi_version }}"
  register: desktop_files
  become: true

- name: Remove all ReadyAPI desktop files
  ansible.builtin.file:
    path:  "{{ item.path }}"
    state: absent
  with_items: "{{ desktop_files.files }}"
  become: true
